name: Release and Publish

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/ai-sdk
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'
          cache: 'pip'
      
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Add uv to PATH
        run: echo "$HOME/.cargo/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: |
          uv pip install -e ".[test]"
      
      - name: Update version
        run: |
          # Get the new version from the release tag
          NEW_VERSION=${GITHUB_REF#refs/tags/v}
          
          # Update the version in __init__.py
          sed -i "s/^__version__ = \".*\"/__version__ = \"$NEW_VERSION\"/" src/ai_sdk/__init__.py
          
          # Commit the changes
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/ai_sdk/__init__.py
          git commit -m "chore: bump version to $NEW_VERSION"
          git push
      
      - name: Build package
        run: poetry build
      
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1 